### ISSUE TITLE
Only 3 of the Wisp Candles burn when 4 are placed together and lit

### ISSUE THREAD

**Issue by ManaStar** [Sheddmer/Abundant-Atmosphere#1]
<img width="509" height="421" alt="Image" src="https://github.com/user-attachments/assets/2d97efcd-896a-437f-bcf4-2391ea4f3f44" />

**Comment by Sheddmer** [comment]
Particle positions have been fixed & made more accurate.

**Comment by ManaStar** [comment]
I think this issue needs to be revisited, this is still present in the current build.

It looks like the lower-most candle is spawning twice as many particles as the others so maybe that's a lead?

<img width="516" height="521" alt="Image" src="https://github.com/user-attachments/assets/21c55fdd-784e-4144-8a0f-76e0adcd1aac" />
